### ISSUE TITLE
Integrate snyk.io

### ISSUE THREAD

**Issue by armins** [aha-oida/aha-secret#12]

**Comment by arusa** [comment]
What exactly should snyk do? I only know it from scanning container images, but it seems it can also scan code for vulnerabilities.

Are there any advantages over brakeman?

There seem to be some ready GitHub actions for brakeman like this: https://github.com/marketplace/actions/brakeman-linter

**Comment by armins** [comment]
Brakeman seems to be equally or better for our setup, i just used snyk in the past.
