### ISSUE TITLE
Make config.yml available outside of docker

### ISSUE THREAD

**Issue by armins** [aha-oida/aha-secret#135]
I would like to configure aha-secrets without entering the docker-container

**Comment by armins** [comment]
Maybe the whole "config" directory?

**Comment by whotwagner** [comment]
you can always get config-files from outside into the container

**Comment by whotwagner** [comment]
I'll write a documentation for that

**Comment by whotwagner** [comment]
https://aha-oida.github.io/aha-secret/docs/installation/docker-compose/
