### ISSUE TITLE
Cookie error

### ISSUE THREAD

**Issue by armins** [aha-oida/aha-secret#67]
On (local) server start a error message is shown:

`Session cookie encryptor error: HMAC is invalid`

**Comment by armins** [comment]
I saw this, when i was on branch `63-add-csrf-tokens`

**Comment by whotwagner** [comment]
This is due to the fact that per default we are creating the secret randomly during startup. Your cached cookie in your browser is after a second startup not valid anymore. If you set `export SESSION_SECRET=...` this won't happen anymore
