### ISSUE TITLE
Automate create_db + rspec

### ISSUE THREAD

**Issue by whotwagner** [aha-oida/aha-secret#9]
If running rspec on a plain installation, it will fail because the database is missing. It would be easier if we could have a automated (rake?)-task that executes:

1. rake db:prepare
2. run rspec

**Comment by armins** [comment]
sounds good in general, but:

```
$ bundle exec rake db:prepare
Starting with Environment: development
rake aborted!
LoadError: cannot load such file -- db/seeds.rb (LoadError)
```

without a seeds file an error is thrown.

What about generating something like `/bin/setup`, like rails does?

**Comment by whotwagner** [comment]
Pullrequest #10 added an empty db/seeds.rb to the repo. So `db:prepare` does not throw erros anymore

**Comment by armins** [comment]
closing this, since #10 was merged & closed already.
